{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<img style=\"float: left; margin: 30px 15px 15px 15px;\" src=\"https://pngimage.net/wp-content/uploads/2018/06/logo-iteso-png-5.png\" width=\"300\" height=\"500\" /> \n",
    "    \n",
    "    \n",
    "### <font color='navy'> Simulación de procesos financieros. \n",
    "\n",
    "**Nombres:** Jose Leonardo Aceves Gonzalez\n",
    "\n",
    "**Fecha:** 10 de octubre del 2011.\n",
    "\n",
    "**Expediente** : 712626.\n",
    "**Profesor:** Oscar David Jaramillo Zuluaga.\n",
    "    \n",
    "**Link Github**: https://github.com/leonardoaceves/Tarea6_JLACEVES_CCORRALES.git\n",
    "\n",
    "# Tarea 6: Clase 10"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "\n",
    "Seguir un procedimiento similar al mostrado cuando se generó una distribución binomial, pero en esta caso genere un código que genere variables aletorias Poisson cuya función de distribución de probabilidad esta dada por:\n",
    "$$P(k,\\lambda)=\\frac{e^{-\\lambda}(\\lambda)^k}{k!}$$\n",
    "    \n",
    "Demuestre matemáticamente que \n",
    "$$P(k+1)=\\frac{\\lambda}{k+1}P(k)$$\n",
    "y a partir de esta relación genere variables aletorias que distribuyen poisson usando el método de la transformada inversa.\n",
    "\n",
    "Enlace: https://es.wikipedia.org/wiki/Distribuci%C3%B3n_de_Poisson\n",
    "    \n",
    "$\n",
    "\\begin{aligned}\n",
    "\\frac{p_{k+1}}{p_k}& = \\frac{e^{-\\lambda}(\\lambda)^k}{k!} \\\\\n",
    "& = \\frac{e^{-\\lambda}(\\lambda)^k}{k!}\n",
    "\\end{aligned}\n",
    "$"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Código de solución Jose Leonardo"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import matplotlib.pyplot as plt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAZIAAAEWCAYAAABMoxE0AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjMuNCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8QVMy6AAAACXBIWXMAAAsTAAALEwEAmpwYAAAueUlEQVR4nO3de3zU1Z3/8ddnZpJMkgnhknBXQKSIN0QoqPVutWp1vbRatdvarr9a26L2sl3d3W633Uvrdre37U2t2tpuxYoVtOrWW7XrDQoIioBcqigkgRBIQm6TZGbO74+ZhACTZO6TZN7PxyMm873N+TLIO+ec7znHnHOIiIikypPvAoiIyPCmIBERkbQoSEREJC0KEhERSYuCRERE0qIgERGRtChIRLLMzGab2VozazGzW8zsAjNbnuC5fzaz47JcRJG0mMaRiGSXmd0L7HfOfSn2ejWw2Dm3IoFzrwY+5pz7SJaLKZIy1UhEsm8asAHAzN4PVCYSIjGPAeeY2aRsFU4kXQoSkSwysz8C5wA/NrNW4CLgT332n2ZmDWZ2ROz1XDNrMrNjAJxzQWANcEHuSy+SGAWJSBY5584FXiTalBUATgA299n/CnAXcL+ZlQK/Br7mnHurz2U2AXNzV2qR5ChIRHJrNNByyLZvAJXAn4Fa4CeH7G+JnScyJClIRHKrEajou8E51w38Ejge+K47/AmYCqApF4UTSYWCRCS33gDe13eDmU0B/hn4BfBdMys55Jw5wOu5KZ5I8hQkIrn1JHBWzwszM6K1kXuBG4A64F/77C8B5gPP5LSUIklQkIjkkHPuNaDZzBbFNt0CTAD+Kdak9Wng02Z2Rmz/XwEvOOdqc19akcRoQKJIjpnZBcDnnXOXJ3DsSuAG59ybWS+YSIoUJCIikhY1bYmISFoUJCIikhYFiYiIpMWX7wLkUlVVlZs+fXq+iyEiMqysWbOmwTlX3d/+ggqS6dOns3r16nwXQ0RkWDGzdwfar6YtERFJi4JERETSoiAREZG0KEhERCQtChIREUmLgkRERNKiIBERkbQoSGTIausM8cuX3+HtPa35LoqIDKCgBiTK8PHS1gZuf+QNdjZ24PMYnzx1OreeN4vKsqJ8F01EDqEaiQwpzR3d3PbwG/z1vSsp9nm49/oFXLVgKr985R3O+q/n+eXL79AdjuS7mCLSR0GtR7JgwQKnKVKGrmc37uYfl6+nobWLG888ilvPm4W/yAvAprr9/NsTG3l5215mVpfzjx+ewzmzxxNdqVZEssnM1jjnFvS7X0Ei+bavrYtv/n4Dj66r5ZiJFfznR+dywtTKw45zzvHspnq+9eQm3mlo44xZVXztw8cye2JFHkotUjgUJH0oSIYW5xxPrK/jnx/dwP5gN4vPmcXnzp5JsW/gFteuUIRfr3iXHz67hdbOENcsPJIvn/8+qgIlOSq5SGFRkPShIBk66vcH+dryN3l6427mTq3kOx+dm3TNorGtix8+t5Vfr3iXsiIv37zsOK48eWqWSixSuBQkfShIhoYXNtdzy5K1dIYifPn893HD6TPweVN/7mNbfSs3L1lLc3sXr/z9eRksqYjA4EGip7Ykp4LdYf7+kfVMGOXnf289g8+eNTOtEAE4enyAU48aR0swlKFSikgyFCSSUw+sfI+65iDf/KvjOKo6kLHrBvw+WrtCRCKFU8MWGSoUJJIz7V0hfvrCNk6bOY7Tjq7K6LUrSnw4B+3d4YxeV0QGpyCRnPnlK9tpaO3iKxe8L+PXDvijkzS0qnlLJOcUJJIT+4Pd3PWntzlndjXzp43N+PUDJbEg6ezO+LVFZGAKEsmJe158h+aObr5yweysXL+nRqIOd5HcU5BI1u1r6+K+l97houMncvyUw0esZ0JFiYJEJF8UJJJ1d/3pL7R1hfjy+ZnvG+nR20fSqSARyTUFiWRV/f4g97+6nctPmsKsCdmbE6u3j0Q1EpGcU5BIVv30hb/QHXZ88YOzsvo+FSXRdUpaVCMRyTkFiWRNTVMHD6x8j6sXTGXauPKsvld5SXS6edVIRHJPQSJZ86PntgKw+Nzs1kYAfF4PpUVePf4rkgcKEsmKdxraWLpmJ9ctOpIpo0tz8p4Bv0+d7SJ5oCCRrPjhs1so8hqfP2dmzt6zosSnx39F8kBBIhm3eVcLj75ey6dOm8H4Cn/O3lc1EpH8UJBIxn3/mS0Ein189syjcvq+gRKfOttF8kBBIhm1fmczf9iwixvOmMGY8uKcvnegRDUSkXxQkEhGffeZzYwuK+KG02fk/L0DfvWRiORDXoPEzC40s81mts3Mbo+z/xgze9XMOs3sb5M5V3Jv9fZ9vLB5DzedNZMKf1HO379CNRKRvMhbkJiZF/gJcBFwLHCtmR17yGH7gFuA/0rhXMkh5xz/9fRmqgIlfPLUaXkpQ09nu3NaJVEkl/JZI1kIbHPOve2c6wIeBC7re4Bzrt45two4dJTZoOdKbr1Zs58Vb+/jc2fPpKzYl5cyBEqKCEccwe5IXt5fpFDlM0imADv6vN4Z25btcyULlq2todjr4aMnTx302K6dNXSsW5fxMvSuSaLR7SI5lc8gsTjbEm2TSPhcM7vRzFab2eo9e/YkXDhJXCgc4bHXazn3mPFUlg3eN1J7+23s/OKXMl6OCs0ALJIX+QySncARfV5PBWozfa5z7m7n3ALn3ILq6uqUCioDe2lbAw2tnVw+b/BKYXDzFjpWryG0Zw8uHM5oOQ4st6sgEcmlfAbJKmCWmc0ws2LgGuCxHJwrGbZ8bQ2VpUWcc8zgQd245IHoD+Ew4aamjJajd3Er1UhEcio/vaKAcy5kZouBpwAvcJ9zboOZ3RTbf6eZTQRWA6OAiJl9ETjWObc/3rl5uZEC19YZ4qkNu7ni5CmU+LwDHhtubaX5sd/jHTeO8N69hBoa8I0bl7Gy9NRItCaJSG7lLUgAnHNPAk8esu3OPj/vItpsldC5kntPb9xFR3eYKxJo1mp+9FFcezvjbr6Z+v/4D0INDTB7dsbKUqEaiUheaGS7pGXZ2lqmjill/pFjBjzOOUfjkiX4jz+einPOBiDc0JDRsqiPRCQ/FCSSsvr9QV7auofLT5qCxxPvQboD2letomvbXxhz7bV4q6J9KaFMB4lfQSKSD3lt2pLh7bHXa4k4Enpaq3HJEjyVlYy6+CLM78f8fkINezNanhKfl2KvR/NtieSYaiSSsuXrajhxaiVHjw8MeFx3fT0tzzzL6CuuwFNaipnhq6rKeI0EeqZJ0YBEkVxSkEhKtu5u4c2a/Vx+0uC1kaalSyEUYsw1H+vdFg2SzA8Q1ZokIrmnIJGULFtbg9djXDp38oDHue5umn77EOWnn07x9Om9271V4whnuGkLtCaJSD4oSCRpkYjj0XW1nDGriuqKkgGPbXn+eUL19Yy57tqDtmezaUt9JCK5pSCRpK3avo+apo6Exo40LlmCb/IkAmedddB2X1U14cZGXHdm+zO0JolI7ilIJGnL19VQVuzl/GMnDHhc59tv0/7qCsZc/THMe/Cod19VdER7aF9jRsvWsyaJiOSOgkSSEuwO8/gbdVx43MRB1x1pfPBBKCpi9Ec/ctg+X1UVQMY73NXZLpJ7ChJJyvNv1dMSDA06diTS3k7zsuWMuuCC3tDoq2dbxke3+32aa0skxxQkkpRla2uorijhA0cfHg59NT/+OJGWFsZ8/Lq4+729NZLMBklFiY+uUITOUGanqBeR/ilIJGFN7V08v7mey+ZOxjvAlCjRebUepGT2bErnzYt7TM+sv5ke3d4z31Zbp4JEJFcUJJKwJ9bX0R12gzZrdaxbR+emTYy59lrM4geOp7QUTyCQhfm2ois0qp9EJHcUJJKw5WtrmDU+wHGTRw14XOOSJXjKy6m89JIBj8vG6PYDa5JomhSRXFGQSEJ27Gtn1fZGLp83pd9aBkBo3z5a/vcPVF5+OZ7y8gGvmY3R7VqTRCT3FCSSkOVra4DBZ/ptevh3uO7uw0ayx+Orqs5805bWJBHJOQWJDMo5x7J1NSyaMZYpo0v7Py4cpunBBylbtIiSmTMHvW42pknRmiQiuacgkUGtr2nm7T1tg06J0vp//0d3bS1jrh28NgLR0e2RlhYinZ2ZKCYQffwX0HxbIjmkIJFBLVtbQ7HPw0UnTBrwuMYlS/BVV1Nx3rkJXTcbgxJVIxHJPQWJDCgUjvD712v54JzxVJYW9Xtc186dtL34EqOvugor6v+4vrIxKLG0yIvH1NkukksKEhnQi9saaGjtGnQBq6alD4MZo6++KuFr+8bFgmRv5p7cMjOtSSKSYwoSGdDytTVUlhZx9uzx/R7jQiGaH3mEwBlnUDRxYsLX9lXHgmRPhqdJ8Repj0QkhxQk0q/WzhBPbdjFJSdOotjX/1+V1j/9idCePYz+2NVJXd83diyQpRmANSBRJGcUJNKvpzfsItgdGfRpraaHluIbP57AmWcmdX0rLsZbWUk4g01boDVJRHJNQSL9Wra2hiPGljJ/2ph+j+muq6P1xRepvPIKzDfw+iTxeKurMt60pTVJRHJLQSJx7d4f5OVtDVxx0sBTojT97hGIRBj90Y+m9D5ZGd2uNUlEckpBInH9/vVaIg4uG6BZy4XDNP3ud5SfdhrFU6em9D6+ceMy+tQWxNZtV41EJGcUJBLXsrU1zJ1ayczqQL/HtL38MqG6OkZfnVwne19ZmSZFj/+K5JSCRA6zZXcLG2r3Dz5B49KleMeOpeLcc1J+L191Fa69nUhbW8rXOFTA76O9K0w44jJ2TRHpn4JEDrNsbQ1ej3HJiZP7Paa7vp6W51+g8orLseLilN+rd3R7Bpu3NAOwSG4pSOQgkYjj0bU1nDGriuqKkn6Pa162HEKhlDvZe/SObs9g81aF5tsSySkFiRzkz9v3UdscHHDsiItEaHr4Ycre/35KZsxI6/2yMbo9UKLldkVySUEiB1m+tobyYi8XHNv/VCftK1fSvWNHWp3sPXy9EzdmbnT7gRmANbpdJBcUJNIr2B3mifV1fOj4iZQWe/s9rmnpUryVlVRccH7a7+kdMwY8noyObg9oTRKRnFKQSK8/vlVPSzA0YLNWqLGRlmeeZdRlf4WnpP8+lESZ14t37NiMNm2pj0Qkt/IaJGZ2oZltNrNtZnZ7nP1mZv8d2/+GmZ3cZ992M1tvZuvMbHVuSz4yLVtbQ3VFCafNrOr3mOblj0bXZL8q8eniB5PpsSS9T22pRiKSE8lPjpQhZuYFfgKcD+wEVpnZY865jX0OuwiYFftaBPws9r3HOc65zI5mK1CNbV28sLme60+djtcTf0oU5xxNDz1E6UknUTJrVsbeO9Oj27VKokhu5bNGshDY5px72znXBTwIXHbIMZcBv3JRK4DRZjbweq+SkifW19EddgMOQuxYs4aud97JSCd7X9EaSeY628uL1Ucikkv5DJIpwI4+r3fGtiV6jAOeNrM1ZnZjf29iZjea2WozW71nT2bXvRhJlq+t4X0TAhw3eVS/xzQtXYonEGDUhR/K6Hv7qqsI72nAucyMRPd6jPJir2okIjmSzyCJ135y6L8kAx3zAefcyUSbv75gZnEXw3DO3e2cW+CcW1BdXZ16aUew9/a2s/rdRi6f1/9Mv+HmZvb/4SlGXXoJnrKyjL6/d1wVrrubSEtLxq4Z8GviRpFcyWeQ7ASO6PN6KlCb6DHOuZ7v9cAyok1lkoLl62oAuGyAddmbf/84rrMzo53sPQ6MJclsh7tqJCK5kc8gWQXMMrMZZlYMXAM8dsgxjwGfjD29dQrQ7JyrM7NyM6sAMLNy4ALgzVwWfqRwzrF8bQ2LZoxlyujSfo9pWroU/3HH4T/22IyXISuj2/1FWpNEJEfy9tSWcy5kZouBpwAvcJ9zboOZ3RTbfyfwJHAxsA1oBz4dO30CsCzWDOMDHnDO/SHHtzAivLGzmbcb2rjxzKP6PSa4fj2dmzcz8ZvfzEoZfOPGARDem8GxJCU+WoMa2S6SC3kLEgDn3JNEw6Lvtjv7/OyAL8Q5721gbtYLWACWra2h2OvhohP6fxiu8aGHsLIyRn34w1kpgzdLTVv1LcGMXU9E+qeR7QWsOxzh96/Xct6c8VSWFsU9Jtzaxv4n/5dRF1+EN1CelXJ4KyuhqCjjo9vV2S6SGwqSAvbS1gb2tnUNOCXK/ieewLW3Z6WTvYd5PFkZlKg+EpHcUJAUsGVraxhdVsTZs8fH3e9CIfbddx8lx87Bf+KJWS2Lb9y4jA5KrIg9tZWpsSki0j8FSYFq7Qzx9MZdfPiESRT74v81aH78cbrefZfqz3++3/ElmZLx+bb8PpyD9q5wxq4pIvEpSArUU2/uItgd6bdZy3V30/DTn1Fy7BwC552X9fJ4q6sIN2RyKvnY4lZq3hLJOgVJgVq+roapY0qZP21M3P3Njz1G93vvUX3zzVmvjUB0yd3Q3r24SCQj1+uZuFHzbYlkn4KkAO3Y187L2xq4op8pUXpqI/4TTiBw9tk5KZOvqgrCYcJNTRm5XkWJZgAWyRUFSQH60R+34vN6+PiiaXH3Ny1bRndNDdU3L85JbQQyP7q9dyp51UhEsk5BUmC2N7Txu9dq+PiiI5lY6T9sv+vqouHOO/HPPZHyM87IWbkyPbq9d3ErrdsuknUKkgLz389tpchrfO7smXH3Nz3yCKHaOqpvviVntRHI/Oh2rdsukjsKkgKyrb6V5etq+OSp0xlfcXhtJNLVRcOdd1E6bx7lHzgtp2Xzxab4z1TTltZtF8kdBUkB+eFzW/EXeflsPxM0Ni1dSmjXLqpvyc2TWn15ysuxkpKMjW4v17rtIjmjICkQm3e18PgbtVx/2nTGBUoO2x/p7GTvXXdTtmABZaeckvPymVlGl9wt8nrwF3lUIxHJAQVJgfjhc1soL/Zx4xn91EZ++xCh+nqqcjRuJB5fVRXhjM4ArDVJRHJBQVIANtQ28+T6XfzNB6Yzprz4sP2Rjg4afn43ZYsWUb4ofwtNequqCGVwdLtmABbJDQVJAfjBs1up8Pu44fT4tZHGB39LeE8D1TcvznHJDpbx+ba03K5ITihIRrj1O5t5ZuNuPnPGUVSWHb7mSKS9nb333EP5aadStmBBHkp4gK+qinBjIy6UmX/8AyWqkYjkgoJkhPveM5sZXVbEpz8wPe7+xiVLCO/dS9Xim3NbsDh81VXgHKF9+zJyPa1JIpIbCpIR7LX3Gnl+8x5uPPMoKvxxaiNtbey9517KTz+dspPn5aGEB/P2jG7PUPNWdE0SjWwXybZBg8TMFptZ/CliZUj7/jNbGFtezPWnTo+7f99vHiDc2Jj3vpEevkyPbldnu0hOJFIjmQisMrOHzOxCy9ezoZKUVdv38eLWBm4666jewXl9hVtb2XfvvZSfdSalc+fmoYSH6x3dnqEntwJaJVEkJwYNEufc14BZwL3Ap4CtZvYtM4s/WZMMCd97egtVgRI+ccr0uPsb/+d/CDc3Uz0E+kZ69EzcmMkaSXfY0RnKzBonIhJfQn0kLvor3a7YVwgYAzxsZt/JYtkkRa/8pYFX397L58+eSWmx97D93XV17L3vFwTOPZfSE47PQwnj85SW4ikvT2l0e3dtLR3r1x+0TWuSiORGIn0kt5jZGuA7wMvACc65zwHzgY9kuXySJOcc339mCxNGlXDdoiMP2x9qbOS9//cZiEQY/5Uv56GEA4uObk++aWvXv3+Ldz/+1wS3bOndpjVJRHIjkRpJFXClc+5DzrmlzrluAOdcBLgkq6WTpL20rYFV2xtZfM7R+IsOro1E2tvZcdNNdO/YwdSf/oSSmUOvddKbwqBEFwrRvnIlrquL2r+7jUhXF6B120VyJZE+kq87597tZ9+mzBdJUuWc47tPb2FypZ+r33/Ewfu6uth5y60E17/JlO99l/KF+ZsKZSCpjG4PbthApLWVysv+is633qLhRz8G0l+T5LlNu7n1wbX85PltPLdpNzsb29VxLxLH4Y/zyLD1x7fqWbejiW9feQIlvgO1EReJUPsP/0jbSy8x8V//hYoPfjCPpRyYr6qKtldfTeqctldXADD+ttuw4mL23nMPgbPPomLi0UDqNZIHVr7H85vrifTJjgq/j2MmVnDMxFHMnljBnEkVvG9CRdxxOiKFQkEyQryyrYFbH1zHjKpyPjp/au925xy777iD/Y8/TvWXvsSYq67KYykH56saR2T/fiJdXXiKD59gMp62lSsomT0b39ixjL/tdtpWrKT2ttspv+83QOrL7dY2Bzln9nh+cM1JbNndwqa6FjbvauGtXftZvrbmoFHz08eVccdHTuSUo8al9F4iw5mCZAR47PVavvJQNETu/5uFFHkPtFjuvfvnNP7q14y9/pOMu/EzeSxlYnqW3A03NOCZPHnQ4yOdnXS8tpYx13wsen6gnMn/cQfv/vUn8P7kB2AfSLlpq665g/nTRlPhL2L+tLHMnza2d59zjtrmIG/V7eetXS0sXb2Dm/5nDb9ffDpHjC1L6f1EhitNkTLM3fvSO9yyZC3zjhjD0s+exqTK0t59jUuXsuf732fUpZdGm32GwVjSZEe3d6xdh+vsPGgxrrKTT2bcZz5D8NFlnFL3ZkpB0tEVpqm9+6A/z77MjCmjSzlvzgS+cM7R/OLTC4lEHJ/51Wra1LkvBUZBMkxFIo5vP7mJf318Ix86bgK/umHhQbP77n/mGXb98zcoP/MMJn/r3zHP8PioDwRJYo8At614Fbxeyt7//oO2V3/h85TMmcOt6x6mO4UBjrXNHQBMHn342vbxzKgq58fXncyW3S387dLXiUTUKS+FY3j86yIH6QpF+MrS17nr/97mr085kp9+fP5Bj/q2rfwztV/5W0pPOIGpP/gBVjR8OoIPBEligxLbV6yk9Pjj8QYCB2234mKm/Od3KOsOctwDP076aatdzUGAfmsk8Zz5vmr+4eI5/O+bu/jRH7cl9X4iw5mCZJhp7Qxxw/2rWLa2hr+94H3862XH4/UcaLIKbtzIzs9/nqIjj+CIu+7EUza82uu9SUyTEm5tpWP9+n7XmC85+miWvf8ypm5aQ9PDDydVjtqmaI1kUmViNZIeN5w+gyvnTeH7z27hqQ27kjpXZLhSkAwje1o6ufbuFbzyl7185yMnsvjcWQf1ewTfeov3bvwsnlGjOPKee/COHp2/wqbIU1yMt7IyodHt7atXQzhM+anxgwTgz/PO591px7L723fQ9d57CZejLlYjmZhkkJgZ37ryBOZOreTLv13H5l0tSZ0vMhwpSIaJd/e28dE7X2FrfQs//+T83gGH4dY2mh5+mO3XXsc7l18BoRBH3nsPRRMn5rnEqUt0dHv7qyuw4mJKTzqp32MC/mIeueBvMK+X2r+7LeHVF+uaO6gKFB80HidR/iIvd31iAWUlPj7zq9U0tnUlfQ2R4URBMgy8sbOJK3/6Cvs7unngM6dwzuzxtK9aRe3tf8/WM86g7mv/RHj/fsZ/9asc9cTjlBwVf2324SLR0e1tK1dSevLJePz91xoCfh+1xaOY+PWv07FuHXvvuTehMtTvaWZRRy3tq1cTCQYTLnuPiZV+7vrEfHY1B1m85DVCYc1ALCNXXseRmNmFwA8BL3CPc+6OQ/ZbbP/FQDvwKefca4mcO1xFIo63G1pZt6OZdTsaWbejiU11LUwc5ef+S6cx+smH+MuyR+h+9z085eVUXnIJoz9yJf65c4fF472J8FVV0fHm+gGPCe3bR+dbb1H9xVsHPC5Q4uPtPSFGXfJhWp//I3t+/GPKzzid0uOO6z0m3NxMcNMmghs3Rb9v2siX//I2Hud493dAURGlxx5L6fz5lC2YT+m8efjGDL7W28lHjuHfrjiev3v4Db715Ft8/dJjE7p/keEmb0FiZl7gJ8D5wE6ii2c95pzb2Oewi4iuhTILWAT8DFiU4LnDQkNrJ+vea2LdjujXGzv2EWlpJdDdQTVdnFjp4brSThZuWUP3Va+yJxKhbOFCqj73OUZdcMGw60xPhK9qHOE9A9dI2leuBKC8n472HgF/dHErM2Pi179O++o11H717xh1yYfpjIVHd03NgfeeMAH/nDn8puRoJs2fyzWnTqfjtbW0r1lD469/zb777gOgeOZMyubPp2z+yZTOX0DRlMlxg/zqBUewqW4/9738DnMmVXDVgiMOO0ZkuLN8TUJnZqcC33DOfSj2+u8BnHPf7nPMXcALzrklsdebgbOB6YOdG8+CBQvc6tWrky7r3V89nfJ3mhI61gD6/JFa7M/XHAd9B/CGwN/pKA3GvneCvzN2jUPsrzDePMHHmyf4aBozslskF67o4uwXuvn+l8voLo5fy7rgD53M2Rjiv79YhvP0XxMLhsJ0hSKMis2FNe2dMFf/NogB+8YY9RM87J7gYfdED7sneOkoMxyOlmAIv89Lse/An7U35JhUF2HKzjBTd0a/+zuj+1rLja7igz/n3i+AiAN3oC057DUiHoh4IeyFiMcIe3p+JvqzByIG7pCvw7ZhB/7S9Pz9sj5lwRH/b5WL/dcO2dJHnNM0QmZ4qj99El/64jMpnWtma5xzC/rbn8+mrSnAjj6vdxKtdQx2zJQEzwXAzG4EbgQ48sjD1+dIRGBPF0dtDyd1jrPDf3aH/E8Z9hpBv9FeAfvGe+j0R193lhhBPwRjr4Olxt5xNuA/mCNJW3n0PsvaHc39BMm0d8PsOMI76J/JoXvfneHlrptKCZYaXSXxz+353erQCkbYZ+w8wsvOI7ysBCziqGpwTNkZZlJtBG/E9fmsLfaPfLQQEXN0x/YXeTx4wg5PmOhXpOdnhycS/QWjKAIlkWgYeHpDyR0cUH2Cqu8vKIf+PYP+//Ef6E/PEkwMc/HfU4aWfSelNudcIvIZJP3/ijT4MYmcG93o3N3A3RCtkSRTwB7X/fLPqZwmKWp98UV2PHEj3zrzXspOnnfY/u7aWrbdcR7H3PRVLr3++gGv9YuX3+Gbv9/I2n86nzHliU0C+cLmej71i1U8fNOpLJg+dvATErR5VwtX/PRl2rsO/qVklN/HjKpypo0rZ3pVOTOqypg+rpwjx5ZRXuLD6zG8ZnhS/EUiHHGEIpHYd4fXDJ/XooFWIL+cCAzcCJyefAbJTqBvg/FUoDbBY4oTOFeGqcFGt7etiPaP9DcQsa9An+V2Ew2SnjEkk0YnPqo9EbMnVvCb/7eIP23Zw5Fjy5g2rpwZVeWMKSvK6oMSXo/h9ST/GLNIovIZJKuAWWY2A6gBrgGuO+SYx4DFZvYg0aarZudcnZntSeBcGaZ6giS8N/6gxPaVK/COHUvJrFmDXqvCn/ziVnVNHXgMJlSUJHxOouYdOYZ5Rw7+xJfIcJK3IHHOhcxsMfAU0Ud473PObTCzm2L77wSeJPro7zaij/9+eqBz83AbkgXeMWPAjFCcJ7ecc7S9uoKyRQsTmogyleV2a5uDjK/w4/OO7IcaRDIlr+NInHNPEg2Lvtvu7POzA76Q6LkyMpjPh3fs2LiDErve2U6ovp7yU05N6FoBf0/TVuIdjXXNHUxKcNZfEdHIdhmifFVVhOI0bbWtiC7DW35K3If0DpPKuu11TcGkJ2sUKWQKEhmSfOPGxe1sb1+xEt/kSRQl+Ch3hf9AZ3sinHPUNQeTmj5epNApSGRI8lVXHTa63UUitK9cSfmiUxJ+yqn3qa0EayTNHd10dIdVIxFJgoJEhqSeGYD7zrwQ3LSJcHPzgNPGH6qs2ItZ4jWS2qboo7+TM/zor8hIpiCRIclXVY3r6iLS2tq7rb1n/MiixIPEzAiU+BLuI6lrTm1BK5FCpiCRIclXFVspsU/zVtuKFRQfdRRFE8Ynda2KEl/iNZJm1UhEkqUgkSHp0NHtrquL9jVrEn5aq6+A35dwH0ldUwc+j1EVyPxgRJGRSkEiQ9Kho9s71q/HtbcnNC3KoQJJ1EjqmoNMGOXHqzmoRBKmIJEhydtTI4k1bbWtWAFmlC9cmPS1Av4iWhLubO9gsgYjiiRFQSJDkreyEny+3tHt7a+uwD9nDt7Ro5O+VkWJj9ZgYiPbNYZEJHkKEhmSzOOJDkrc20Cko4P211+nLInHfvtKtGkrEnHsag5qehSRJClIZMiKjm5voH3Na9DdPeiyuv1JtLN9b1sXXeEIk1UjEUmKgkSGLG9sdHv7yhXg81E2f35K1wmU+GjrChOODLyuWc8YkokaQyKSFAWJDFk9Eze2vbqC0rlz8ZSVpXSdnvm22roGrpX0jmpXjUQkKQoSGbJ846LTpAQ3bky5WQsSn2+rd1S7+khEkpLX9UhEBuKrqoJwdH3zVAYi9ggkOANwXXOQYp+HcQkuySsiUaqRyJDlq46OJTG/n9K5c1O+TqJrkkQf/fVndf10kZFIQSJDlndcdL6tsvnzseLUawmJrklS19ShyRpFUqAgkSGraHx0csZkpo2Pp3fd9gRqJOpoF0me+khkyCqePp3J//mfVJx7TlrXSWTd9nDEsWu/BiOKpEJBIkNa5aWXpH2NRPpI9rR0Eo44TY8ikgI1bcmI1/v47wB9JLWxR381YaNI8hQkMuJ5PUZZsXfAPpK62GBE1UhEkqcgkYIw2MSNPYMR1dkukjwFiRSEgN834JoktU1Byoq9jCpVt6FIshQkUhCia5IMXCOZqMGIIilRkEhBCPgHbtqq1RgSkZQpSKQgBAarkWhUu0jKFCRSEAIlRf3WSLpCEfa0djJptGokIqlQkEhBqPD7aOln3fbd+4M4B5NVIxFJiYJECkJFrI/EucNXSaxrjo0hUY1EJCUKEikIgRIfEQcd3eHD9h0YQ6IaiUgqFCRSEHonbozT4a4aiUh6FCRSEHonbozT4V7X1EGF39d7jIgkR0EiBaFigBqJxpCIpEdBIgWhd3GreDWS5g6tQyKShrwEiZmNNbNnzGxr7PuYfo670Mw2m9k2M7u9z/ZvmFmNma2LfV2cu9LLcDTQmiR1TUHN+iuShnzVSG4HnnPOzQKei70+iJl5gZ8AFwHHAtea2bF9Dvm+c+6k2NeTuSi0DF/9rdse7A6zt61Lo9pF0pCvILkMuD/28/3A5XGOWQhsc8697ZzrAh6MnSeStN7FrQ4ZlLir54ktBYlIyvIVJBOcc3UAse/j4xwzBdjR5/XO2LYei83sDTO7r7+mMQAzu9HMVpvZ6j179mSi7DIMlfezSuKBlRHVtCWSqqwFiZk9a2ZvxvlKtFYRbz7vnmHJPwNmAicBdcB3+7uIc+5u59wC59yC6urqZG5BRpBin4cSn+ewx38PrIyoGolIqrL24Lxz7oP97TOz3WY2yTlXZ2aTgPo4h+0EjujzeipQG7v27j7X+jnweGZKLSNZhf/wGYB7RrWrs10kdflq2noMuD728/XAo3GOWQXMMrMZZlYMXBM7j1j49LgCeDOLZZURIt5yu7XNQcaUFVFa7M1TqUSGv3wN5b0DeMjMbgDeA64CMLPJwD3OuYudcyEzWww8BXiB+5xzG2Lnf8fMTiLa1LUd+GyOyy/DUCBejaSpQ7URkTTlJUicc3uB8+JsrwUu7vP6SeCwR3udc5/IagFlRAqUHL5ue11zkKljFCQi6dDIdikYgZKiw2oktaqRiKRNQSIFo+KQddvbOkPsD4Y0PYpImhQkUjAO7WzvmT5eEzaKpEdBIgXj0M72A4/+qkYikg4FiRSMQImPrnCEzlB0lcSewYga1S6SHgWJFIxD1yTpmR5l/KiSvJVJZCRQkEjBCBwy31ZdU5CqQAklPg1GFEmHgkQKxqFrktQ2dzBZT2yJpE1BIgUjcMiaJHXNQXW0i2SAgkQKRkXPcrvBEM45TY8ikiEKEikYfWsk+4Mh2rrCatoSyQAFiRSM3j6SzpCmjxfJIAWJFIy+j/8eGEOiGolIuhQkUjBKfB58HqO1s7t3DIlqJCLpU5BIwTCz3mlS6pqCeAzGV2gwoki68rWwlUhe9KxJ0tIZYsIoPz6vfpcSSZeCRApKoCRaI2kJhjSGRCRD9OuYFJSeNUl27Q+qf0QkQxQkUlACJT5agqHYyoiqkYhkgoJECkrAX8SOxnY6QxEmafp4kYxQkEhBCZT4aGrvBmCyaiQiGaEgkYLSMygRUI1EJEMUJFJQeqZJAdVIRDJFQSIFpSdIirxGVUCDEUUyQUEiBaVnBuAJo/x4PJbn0oiMDAoSKSgVsRrJZI0hEckYBYkUlJ4aySTN+iuSMQoSKSg9fSQa1S6SOQoSKSg9j/9qHRKRzFGQSEGZURXgc2fP5MLjJ+a7KCIjhmb/lYLi9Ri3XXhMvoshMqKoRiIiImlRkIiISFoUJCIikhYFiYiIpCUvQWJmY83sGTPbGvs+pp/j7jOzejN7M5XzRUQk+/JVI7kdeM45Nwt4LvY6nl8CF6ZxvoiIZFm+guQy4P7Yz/cDl8c7yDn3f8C+VM8XEZHsy1eQTHDO1QHEvo/P8fkiIpIhWRuQaGbPAvGGD/9jtt6zn3LcCNwYe9lqZptTvFQV0JCZUg0ZI+2eRtr9wMi7p5F2PzDy7ine/Uwb6ISsBYlz7oP97TOz3WY2yTlXZ2aTgPokL5/w+c65u4G7k7z+YcxstXNuQbrXGUpG2j2NtPuBkXdPI+1+YOTdUyr3k6+mrceA62M/Xw88muPzRUQkQ/IVJHcA55vZVuD82GvMbLKZPdlzkJktAV4FZpvZTjO7YaDzRUQk9/IyaaNzbi9wXpzttcDFfV5fm8z5WZZ289gQNNLuaaTdD4y8expp9wMj756Svh9zzmWjICIiUiA0RYqIiKRFQSIiImlRkCTAzC40s81mts3Mhv10LGa23czWm9k6M1ud7/KkIt48bMN5DrZ+7ucbZlYT+5zWmdnFA11jKDGzI8zseTPbZGYbzOzW2Pbh/Bn1d0/D8nMyM7+Z/dnMXo/dzzdj25P+jNRHMggz8wJbiD4dthNYBVzrnNuY14Klwcy2Awucc8N2EJWZnQm0Ar9yzh0f2/YdYJ9z7o5Y4I9xzt2Wz3Imqp/7+QbQ6pz7r3yWLRWx8V2TnHOvmVkFsIboVEafYvh+Rv3d09UMw8/JzAwod861mlkR8BJwK3AlSX5GqpEMbiGwzTn3tnOuC3iQ6Fxfkkf9zMM2bOdgG2BeuWHJOVfnnHst9nMLsAmYwvD+jPq7p2HJRbXGXhbFvhwpfEYKksFNAXb0eb2TYfyXJ8YBT5vZmtgUMiPFSJyDbbGZvRFr+ho2zUB9mdl0YB6wkhHyGR1yTzBMPycz85rZOqKzgzzjnEvpM1KQDM7ibBvu7YEfcM6dDFwEfCHWrCJDz8+AmcBJQB3w3byWJgVmFgB+B3zRObc/3+XJhDj3NGw/J+dc2Dl3EjAVWGhmx6dyHQXJ4HYCR/R5PRWozVNZMiI28BPnXD2wjGjz3UiwO9aO3dOenewcbkOKc2537H/0CPBzhtnnFGt3/x3wG+fcI7HNw/ozindPw/1zAnDONQEvEF3/KenPSEEyuFXALDObYWbFwDVE5/oalsysPNZRiJmVAxcAbw581rAxouZg6/mfOeYKhtHnFOvIvRfY5Jz7Xp9dw/Yz6u+ehuvnZGbVZjY69nMp8EHgLVL4jPTUVgJij/P9APAC9znn/j2/JUqdmR1FtBYC0SlyHhiO9xObh+1solNe7wb+GVgOPAQcCbwHXOWcGxYd2P3cz9lEm0scsB34bE/b9VBnZqcDLwLrgUhs8z8Q7VMYrp9Rf/d0LcPwczKzE4l2pnuJVioecs79i5mNI8nPSEEiIiJpUdOWiIikRUEiIiJpUZCIiEhaFCQiIpIWBYmIiKRFQSIiImlRkIiISFoUJCJ5ZGbvj03254/NOrAh1fmORPJFAxJF8szM/g3wA6XATufct/NcJJGkKEhE8iw2h9sqIAic5pwL57lIIklR05ZI/o0FAkAF0ZqJyLCiGolInpnZY0RX3pxBdCnXxXkukkhSfPkugEghM7NPAiHn3ANm5gVeMbNznXN/zHfZRBKlGomIiKRFfSQiIpIWBYmIiKRFQSIiImlRkIiISFoUJCIikhYFiYiIpEVBIiIiafn/eiVYiMMppKwAAAAASUVORK5CYII=\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "def factorial(k):\n",
    "    fact = 1\n",
    "    for i in range(1,k+1):\n",
    "        fact = fact * i\n",
    "    return(fact)\n",
    "\n",
    "def function(k,l):\n",
    "    return((np.exp(-l) * l**k)/(factorial(k)))\n",
    "\n",
    "#Parametros\n",
    "k, k1, k2, k3 = np.random.randint(0,40), np.random.randint(0,40), np.random.randint(0,40), np.random.randint(0,40)\n",
    "l = np.arange(0,30)\n",
    "x = l\n",
    "y = function(k, l)\n",
    "y2 = function(k1, l)\n",
    "y3 = function(k2, l)\n",
    "y4 = function(k3, l)\n",
    "\n",
    "#Ploteamos la función\n",
    "#fig = figure(num=None, figsize=(6, 5), dpi=80, facecolor='w', edgecolor='k')\n",
    "plt.plot(x,y)\n",
    "plt.plot(x,y2)\n",
    "plt.plot(x,y3)\n",
    "plt.plot(x,y4)\n",
    "plt.title('f(x)')\n",
    "plt.xlabel('x')\n",
    "plt.ylabel('y')\n",
    "plt.show()\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Código de solución estudiante 2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3418, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-2-5c6ebc7100d6>\", line 2, in <module>\n",
      "    from scipy import optimize\n",
      "  File \"<frozen importlib._bootstrap>\", line 991, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 914, in _find_spec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1342, in find_spec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1311, in _get_spec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1275, in _path_importer_cache\n",
      "PermissionError: [Errno 1] Operation not permitted\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'PermissionError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1170, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 1503, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 1461, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 708, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 737, in getmodule\n",
      "    file = getabsfile(object, _filename)\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 721, in getabsfile\n",
      "    return os.path.normcase(os.path.abspath(_filename))\n",
      "  File \"/opt/anaconda3/lib/python3.8/posixpath.py\", line 379, in abspath\n",
      "    cwd = os.getcwd()\n",
      "PermissionError: [Errno 1] Operation not permitted\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3418, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-2-5c6ebc7100d6>\", line 2, in <module>\n",
      "    from scipy import optimize\n",
      "  File \"<frozen importlib._bootstrap>\", line 991, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 914, in _find_spec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1342, in find_spec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1311, in _get_spec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1275, in _path_importer_cache\n",
      "PermissionError: [Errno 1] Operation not permitted\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'PermissionError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3338, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3435, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2047, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1436, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1336, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1193, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1151, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1170, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 1503, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 1461, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 708, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 737, in getmodule\n",
      "    file = getabsfile(object, _filename)\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 721, in getabsfile\n",
      "    return os.path.normcase(os.path.abspath(_filename))\n",
      "  File \"/opt/anaconda3/lib/python3.8/posixpath.py\", line 379, in abspath\n",
      "    cwd = os.getcwd()\n",
      "PermissionError: [Errno 1] Operation not permitted\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3418, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-2-5c6ebc7100d6>\", line 2, in <module>\n",
      "    from scipy import optimize\n",
      "  File \"<frozen importlib._bootstrap>\", line 991, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 914, in _find_spec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1342, in find_spec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1311, in _get_spec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1275, in _path_importer_cache\n",
      "PermissionError: [Errno 1] Operation not permitted\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'PermissionError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3338, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3435, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2047, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1436, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1336, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1193, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1151, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2923, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3146, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3357, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2047, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1436, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1336, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1211, in structured_traceback\n",
      "    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1151, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1170, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 1503, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 1461, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 708, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 737, in getmodule\n",
      "    file = getabsfile(object, _filename)\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 721, in getabsfile\n",
      "    return os.path.normcase(os.path.abspath(_filename))\n",
      "  File \"/opt/anaconda3/lib/python3.8/posixpath.py\", line 379, in abspath\n",
      "    cwd = os.getcwd()\n",
      "PermissionError: [Errno 1] Operation not permitted\n"
     ]
    }
   ],
   "source": [
    "from math import factorial as fac\n",
    "from scipy import optimize\n",
    "from scipy.stats import beta\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Código de solución estudiante 2\n",
    "def poisson(k,l):\n",
    "    return((np.exp(-l) * l**k)/(fac(k)))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "ERROR! Session/line number was not unique inTraceback (most recent call last):\n",
      " database. History logging moved to new session 110\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3418, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-2-9415d7ad0f67>\", line 2, in <module>\n",
      "    k = np.random.randint(0,40)\n",
      "NameError: name 'np' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'NameError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1170, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 1503, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 1461, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 708, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 737, in getmodule\n",
      "    file = getabsfile(object, _filename)\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 721, in getabsfile\n",
      "    return os.path.normcase(os.path.abspath(_filename))\n",
      "  File \"/opt/anaconda3/lib/python3.8/posixpath.py\", line 379, in abspath\n",
      "    cwd = os.getcwd()\n",
      "PermissionError: [Errno 1] Operation not permitted\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3418, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-2-9415d7ad0f67>\", line 2, in <module>\n",
      "    k = np.random.randint(0,40)\n",
      "NameError: name 'np' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'NameError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3338, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3435, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2047, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1436, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1336, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1193, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1151, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1170, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 1503, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 1461, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 708, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 737, in getmodule\n",
      "    file = getabsfile(object, _filename)\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 721, in getabsfile\n",
      "    return os.path.normcase(os.path.abspath(_filename))\n",
      "  File \"/opt/anaconda3/lib/python3.8/posixpath.py\", line 379, in abspath\n",
      "    cwd = os.getcwd()\n",
      "PermissionError: [Errno 1] Operation not permitted\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3418, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-2-9415d7ad0f67>\", line 2, in <module>\n",
      "    k = np.random.randint(0,40)\n",
      "NameError: name 'np' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'NameError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3338, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3435, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2047, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1436, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1336, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1193, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1151, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2923, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3146, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3357, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2047, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1436, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1336, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1211, in structured_traceback\n",
      "    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1151, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1170, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 1503, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 1461, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 708, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 737, in getmodule\n",
      "    file = getabsfile(object, _filename)\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 721, in getabsfile\n",
      "    return os.path.normcase(os.path.abspath(_filename))\n",
      "  File \"/opt/anaconda3/lib/python3.8/posixpath.py\", line 379, in abspath\n",
      "    cwd = os.getcwd()\n",
      "PermissionError: [Errno 1] Operation not permitted\n"
     ]
    }
   ],
   "source": [
    "#Parametros\n",
    "k = np.random.randint(0,40)\n",
    "l = np.arange(0,30)\n",
    "y = poisson(k, l)\n",
    "plt.plot(l,y)\n",
    "plt.title('f(x)')\n",
    "plt.xlabel('x')\n",
    "plt.ylabel('y')\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
